name: 'Chromatic Deployment'

on: push

jobs:
  chromatic-deployment:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          # https://www.chromatic.com/docs/github-actions#available-options
          projectToken: ${{ secrets.CHROMATIC_DEPLOY }}
          buildScriptName: storybook:build
          storybookBuildDir: storybook-static
          storybookConfigDir: .storybook
          zip: true