name: 'Chromatic Deployment'

on: push

jobs:
  chromatic-deployment:
    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, 'docs-only') }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]

    steps:
      - name: Specify Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_DEPLOY }}
          buildScriptName: storybook:build
          storybookConfigDir: .storybook
          zip: true
